language: go
go: "1.11.5"

if: tag IS present

env:
  - GO111MODULE=on

install: true

notifications:
  email: false

script:
  - GOOS=linux GOARCH=amd64 go build --tags="pow_avx" -ldflags="-s -w" -v -o confbox
  - md5sum confbox.sh

after_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t lucamoser/confbox:$TRAVIS_TAG .
  - docker push lucamoser/confbox:$TRAVIS_TAG